language = "C"

[parse]
parse_deps = false
exclude = []

[defines]
"feature ffi" = "FEATURE_FFI"
"feature client" = "FEATURE_CLIENT"
"feature yaml" = "FEATURE_YAML"
"feature protobuf" = "FEATURE_PROTOBUF"

[export]
include = []
exclude = []
